### ISSUE TITLE
[Path] Add Dependency "farming"

### ISSUE THREAD

**Issue by AntumDeluge** [Darcidride/minetest-spidermob-v1#2]
I wanted to suggest the following patch with creates "depends.txt" and adds "farming" as a dependency since spiders drop "farming:string".

[spidermob-depends.txt.diff.zip](https://github.com/Darcidride/minetest-spidermob-v1/files/416842/spidermob-depends.txt.diff.zip)

**Comment by BetterToAutomateTheWorld** [comment]
You're right, thank you for your suggestion :)
https://github.com/Darcidride/minetest-spidermob-v1/commit/c72d2ff3091c231a15692d774b04764328892190

But be carful, this mod isn't update since a long time with the mobs redo API, i works with Minetest 0.4.14 easily, but can works with better performances if extracted from mobs redo.
